version: "3.8"

services:
  db:
    container_name: mysql
    image: mysql/mysql-server:8.0
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${MYSQL_DB_NAME}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_USER_NAME: ${MYSQL_USER}
      MYSQL_USER_PASSWORD: ${MYSQL_PASSWORD}
      TZ: 'Asia/Seoul'
    ports: # 외부 포트 : 내부 포트
      - "3307:3306"
    volumes:
      - ./mysql/conf.d:/etc/mysql/conf.d # MySQL 설정 파일 위치
    networks:
      - ww_network

  backend:
    container_name: spring
    restart: on-failure
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USER}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}
    depends_on:
      - db
    networks:
      - ww_network

networks:
  ww_network: